// Shared pieces of the M16 service layer (docs/SYSTEM.md §12):
//  - unit files: a minimal TOML subset, hand-parsed (no external crates;
//    everything on the phone is static musl)
//  - the launcher app registry (`/var/apps/<id>/app.toml`, §12.3)
//  - ctl-protocol paths shared by aginx-svcd and aginx-svc (N4③b)
//
// Both parsers are deliberately tiny and lenient: values may be quoted or
// bare words, `#` comments, string arrays on one line. Unit files live in
// /etc/agsvc.d/*.toml (base image) and /var/lib/agpkg/units/*.toml
// (generated by agpkg from manifest service declarations — same name in
// the later dir wins).

use std::collections::HashMap;
use std::fs::OpenOptions;
use std::io::Write;
use std::path::Path;

/// aginx-svcd's control socket (§12.2: "ctl.sock 归 svcd"). Every other
/// service gets /run/svc/<name>.sock when it adopts the socket contract.
pub const CTL_SOCK: &str = "/run/svc/ctl.sock";
pub const UNIT_DIRS: [&str; 2] = ["/etc/agsvc.d", "/var/lib/agpkg/units"];
pub const APPS_DIR: &str = "/var/apps";
pub const LOG_DIR: &str = "/var/log/agsvc";

// Restart-policy defaults (§12.1: 指数退避重启、上限熔断).
pub const BACKOFF_START_MS: u64 = 100;
pub const BACKOFF_MAX_MS: u64 = 10_000;
/// Circuit breaker: this many exits within the window parks the unit in
/// `failed` until an explicit `aginx-svc start`.
pub const BREAKER_N: usize = 5;
pub const BREAKER_WINDOW_S: u64 = 60;
/// An exit sooner than this after spawn counts as a crash-loop failure for
/// backoff growth; a later exit still counts toward the breaker but resets
/// the exponent (the service ran stably for a while first).
pub const STABLE_S: u64 = 10;
/// `type = simple` units become ready after surviving this long.
pub const SIMPLE_GRACE_MS: u64 = 2_000;
/// Binaries missing at spawn time (pre-provisioning) are re-checked at
/// this period instead of counting as failures.
pub const ABSENT_RECHECK_MS: u64 = 30_000;
/// A unit whose weak dependency is still `starting` retries its spawn
/// check at this period (§12.1: readiness blocking IS the ordering).
pub const DEP_WAIT_MS: u64 = 250;

pub fn log_path(name: &str) -> String {
    format!("{LOG_DIR}/{name}.log")
}

pub fn kmsg(s: &str) {
    if let Ok(mut f) = OpenOptions::new().write(true).open("/dev/kmsg") {
        let _ = f.write_all(s.as_bytes());
    }
}

// ---------------------------------------------------------------- parsing

#[derive(Debug, Clone, PartialEq)]
pub enum Val {
    Str(String),
    Bool(bool),
    Arr(Vec<String>),
}

impl Val {
    pub fn as_str(&self) -> Option<&str> {
        if let Val::Str(s) = self {
            Some(s)
        } else {
            None
        }
    }
    pub fn as_bool(&self) -> Option<bool> {
        if let Val::Bool(b) = self {
            Some(*b)
        } else {
            None
        }
    }
    pub fn as_arr(&self) -> Option<&[String]> {
        if let Val::Arr(a) = self {
            Some(a)
        } else {
            None
        }
    }
}

/// section -> key -> value. Keys before any `[section]` line land in the
/// `""` section — that is how the flat app-registry files parse.
pub type Doc = HashMap<String, HashMap<String, Val>>;

pub fn parse_tomlish(src: &str) -> Result<Doc, String> {
    let mut doc: Doc = HashMap::new();
    let mut sec = String::new();
    doc.entry(sec.clone()).or_default();
    for (i, raw) in src.lines().enumerate() {
        let l = raw.trim();
        if l.is_empty() || l.starts_with('#') {
            continue;
        }
        if l.starts_with('[') && l.ends_with(']') {
            sec = l[1..l.len() - 1].trim().to_string();
            doc.entry(sec.clone()).or_default();
            continue;
        }
        let (k, v) = l
            .split_once('=')
            .ok_or_else(|| format!("line {}: expected key = value", i + 1))?;
        let k = k.trim();
        if k.is_empty() {
            return Err(format!("line {}: empty key", i + 1));
        }
        doc.entry(sec.clone())
            .or_default()
            .insert(k.to_string(), parse_val(v.trim())?);
    }
    Ok(doc)
}

fn parse_val(v: &str) -> Result<Val, String> {
    if let Some(rest) = v.strip_prefix('"') {
        let end = rest
            .find('"')
            .ok_or_else(|| format!("unterminated string: {v}"))?;
        return Ok(Val::Str(rest[..end].to_string()));
    }
    if v == "true" {
        return Ok(Val::Bool(true));
    }
    if v == "false" {
        return Ok(Val::Bool(false));
    }
    if let Some(rest) = v.strip_prefix('[') {
        let inner = rest
            .strip_suffix(']')
            .ok_or_else(|| format!("unterminated array: {v}"))?;
        let mut out = Vec::new();
        for item in inner.split(',') {
            let item = item.trim();
            if item.is_empty() {
                continue;
            }
            match parse_val(item)? {
                Val::Str(s) => out.push(s),
                _ => return Err(format!("array items must be strings: {v}")),
            }
        }
        return Ok(Val::Arr(out));
    }
    Ok(Val::Str(v.to_string()))
}

fn field<'a>(doc: &'a Doc, sec: &str, key: &str) -> Option<&'a Val> {
    doc.get(sec).and_then(|m| m.get(key))
}

// ------------------------------------------------------------------ units

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SvcType {
    /// Child writes 1 byte to the fd in env AGINX_SVC_NOTIFY (fd 3) when ready;
    /// EOF on the pipe = died before ready. Redox-init contract (§12.1).
    Notify,
    /// Ready when /run/svc/<name>.sock appears — for binaries that adopt
    /// the socket contract but not the notify protocol.
    Socket,
    /// Foreign daemons that speak neither contract: alive + grace = ready.
    Simple,
    /// Run to completion; exit 0 = done. Restart policy decides on nonzero.
    Oneshot,
    /// Like oneshot but never gates anything on its completion.
    OneshotAsync,
}

impl SvcType {
    fn parse(s: &str) -> Result<SvcType, String> {
        match s {
            "notify" => Ok(SvcType::Notify),
            "socket" => Ok(SvcType::Socket),
            "simple" => Ok(SvcType::Simple),
            "oneshot" => Ok(SvcType::Oneshot),
            "oneshot_async" => Ok(SvcType::OneshotAsync),
            other => Err(format!("unknown type: {other}")),
        }
    }
}

#[derive(Debug, Clone)]
pub struct Unit {
    pub name: String,
    pub cmd: String,
    pub args: Vec<String>,
    /// Extra K=V env entries, applied on top of the base PATH/HOME set.
    pub envs: Vec<String>,
    /// KEY=VALUE lines re-read at every spawn (so a re-provisioned
    /// /etc/aginx/env takes effect on the next restart, no reboot).
    pub env_file: Option<String>,
    pub ty: SvcType,
    /// Weak dependencies: if a listed unit exists and is still `starting`,
    /// hold this one until it resolves (ready OR any terminal state).
    pub requires_weak: Vec<String>,
    pub restart: bool,
    pub autostart: bool,
    pub src_path: String,
    pub src_bytes: Vec<u8>,
}

impl Unit {
    pub fn is_oneshot(&self) -> bool {
        matches!(self.ty, SvcType::Oneshot | SvcType::OneshotAsync)
    }
}

/// Load units from all dirs, later dirs overriding same-name units
/// (agpkg-generated overrides base-image defaults). Filename order within
/// a dir is the declaration order; runtime ordering is enforced by
/// requires_weak + readiness blocking, not by this order.
pub fn load_units(dirs: &[&str]) -> Vec<Unit> {
    let mut by_name: HashMap<String, Unit> = HashMap::new();
    for d in dirs {
        let rd = match std::fs::read_dir(d) {
            Ok(r) => r,
            Err(_) => continue, // /var/lib/agpkg/units before first provisioning
        };
        let mut files: Vec<std::path::PathBuf> = rd
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("toml"))
            .collect();
        files.sort();
        for p in files {
            let stem = p
                .file_stem()
                .and_then(|s| s.to_str())
                .unwrap_or_default()
                .to_string();
            if stem.is_empty() {
                continue;
            }
            let bytes = match std::fs::read(&p) {
                Ok(b) => b,
                Err(_) => continue,
            };
            let src = String::from_utf8_lossy(&bytes).into_owned();
            match unit_from(&stem, &src) {
                Ok(mut u) => {
                    u.src_path = p.display().to_string();
                    u.src_bytes = bytes;
                    by_name.insert(u.name.clone(), u);
                }
                Err(e) => kmsg(&format!("aginx-svcd: bad unit {}: {e}\n", p.display())),
            }
        }
    }
    let mut v: Vec<Unit> = by_name.into_values().collect();
    v.sort_by(|a, b| a.name.cmp(&b.name));
    v
}

fn unit_from(stem: &str, src: &str) -> Result<Unit, String> {
    let doc = parse_tomlish(src)?;
    let name = field(&doc, "unit", "name")
        .and_then(|v| v.as_str())
        .unwrap_or(stem)
        .to_string();
    let svc = doc.get("service").cloned().unwrap_or_default();
    let s = |k: &str| svc.get(k);
    let cmd = s("cmd")
        .and_then(|v| v.as_str())
        .ok_or("service.cmd missing")?
        .to_string();
    let ty = SvcType::parse(s("type").and_then(|v| v.as_str()).unwrap_or("simple"))?;
    let restart = s("restart").and_then(|v| v.as_bool()).unwrap_or(true);
    Ok(Unit {
        name,
        cmd,
        args: s("args").and_then(|v| v.as_arr()).map(|a| a.to_vec()).unwrap_or_default(),
        envs: s("envs").and_then(|v| v.as_arr()).map(|a| a.to_vec()).unwrap_or_default(),
        env_file: s("env_file").and_then(|v| v.as_str()).map(str::to_string),
        ty,
        requires_weak: s("requires_weak")
            .and_then(|v| v.as_arr())
            .map(|a| a.to_vec())
            .unwrap_or_default(),
        restart: restart && !matches!(ty, SvcType::Oneshot | SvcType::OneshotAsync),
        autostart: s("autostart").and_then(|v| v.as_bool()).unwrap_or(true),
        src_path: String::new(),
        src_bytes: Vec::new(),
    })
}

// --------------------------------------------------------- app registry
//
// §12.3: every app is a flat key=value file the launcher scans —
// /var/apps/<id>/app.toml with name/binary/args/scale (category/icon/
// accept are reserved for later). New launcher entry = drop a file, no OS
// source change. aterm consumes this via scan_apps(); /etc/init.d/
// app-registry seeds it from /etc/apps.d while the binary exists.

#[derive(Debug, Clone)]
pub struct AppEntry {
    pub id: String,
    pub name: String,
    pub binary: String,
    pub args: Vec<String>,
    pub scale: usize,
}

pub fn parse_app(id: &str, src: &str) -> Result<AppEntry, String> {
    let doc = parse_tomlish(src)?;
    let root = doc.get("").cloned().unwrap_or_default();
    let binary = root
        .get("binary")
        .and_then(|v| v.as_str())
        .ok_or("binary missing")?
        .to_string();
    if binary.is_empty() {
        return Err("binary empty".into());
    }
    Ok(AppEntry {
        id: id.to_string(),
        name: root
            .get("name")
            .and_then(|v| v.as_str())
            .unwrap_or(&id)
            .to_string(),
        binary,
        args: root
            .get("args")
            .and_then(|v| v.as_str())
            .map(|a| a.split_whitespace().map(str::to_string).collect())
            .unwrap_or_default(),
        scale: root
            .get("scale")
            .and_then(|v: &Val| v.as_str())
            .and_then(|s| s.parse().ok())
            .unwrap_or(3),
    })
}

/// Scan a registry dir (sorted by id for a stable launcher order). Bad
/// files are skipped with a kmsg note, never fatal — one broken app must
/// not take out the launcher.
pub fn scan_apps(dir: &str) -> Vec<AppEntry> {
    let rd = match std::fs::read_dir(dir) {
        Ok(r) => r,
        Err(_) => return Vec::new(),
    };
    let mut out = Vec::new();
    for e in rd.filter_map(|e| e.ok()).map(|e| e.path()) {
        if !e.is_dir() {
            continue;
        }
        let id = match e.file_name().and_then(|n| n.to_str()) {
            Some(s) => s.to_string(),
            None => continue,
        };
        let f = e.join("app.toml");
        let src = match std::fs::read_to_string(&f) {
            Ok(s) => s,
            Err(_) => continue,
        };
        match parse_app(&id, &src) {
            Ok(a) => out.push(a),
            Err(err) => kmsg(&format!("aginx-svcd: bad app {}: {err}\n", f.display())),
        }
    }
    out.sort_by(|a, b| a.id.cmp(&b.id));
    out
}

pub fn socket_for(name: &str) -> String {
    format!("/run/svc/{name}.sock")
}

pub fn path_exists(p: &str) -> bool {
    Path::new(p).exists()
}
