//! aginx 入网钩子 — 把已安装的分身暴露到本地 agent:// 网络。
//!
//! aginx 网关靠扫 `~/.aginx/agents/*/aginx.toml` 发现可拉起的 agent
//! （`aginx::config::agents_dir`，深度 5）。`clone_install_files` 每次安装
//! 写一份，command 指向本二进制的绝对路径 `aginx-carrier acp --clone
//! <name>`（绝对路径通过网关的 discovery 校验，不吃 PATH 亏）；`kill_agent`
//! 删掉它，网络侧不再列出已卸载的分身。boot 时 workspace 扫描出来的分身
//! 注册同步随 `start` 子命令落地（Phase 5+）再补。
//!
//! 写入失败不致命（分身照常装好），只 warn —— aginx 网关不存在不该挡安装。

use serde::Serialize;

/// `~/.aginx/agents/` — 与 aginx 网关 `config::agents_dir()` 同一约定
/// （网关硬编码 `~/.aginx`，不吃 AGINX_CARRIER_HOME）。
fn default_agents_root() -> std::path::PathBuf {
    dirs::home_dir()
        .unwrap_or_else(std::env::temp_dir)
        .join(".aginx")
        .join("agents")
}

/// The `aginx.toml` shape the gateway's discovery parser expects
/// (`aginx::agent::discovery::AgentConfig`): `id`/`name` required non-empty,
/// `command.path` must be a bare name or an absolute existing path.
#[derive(Serialize)]
struct AgentToml {
    id: String,
    name: String,
    agent_type: String,
    #[serde(skip_serializing_if = "String::is_empty")]
    description: String,
    #[serde(skip_serializing_if = "String::is_empty")]
    version: String,
    /// stdout 方言声明（ACP.md §2.8）：ask 模式发 claude-stream-json 事件行，
    /// 网关翻译器收割 session_id/成本——统一 aginx 流程的会话契约。
    output: String,
    command: CommandToml,
    session: SessionToml,
}

#[derive(Serialize)]
struct CommandToml {
    path: String,
    args: Vec<String>,
}

/// `resume_args` 只在网关拿到 sessionId 时追加（`--session <id>`）——
/// carrier 侧 label = `aginx:<id>` 跨进程续接。
#[derive(Serialize)]
struct SessionToml {
    resume_args: Vec<String>,
}

/// Write `~/.aginx/agents/<name>/aginx.toml` registering the freshly
/// installed clone. `display_name`/`description`/`version` come from the
/// clone's definition layer; empty display falls back to the clone name
/// (gateway rejects empty `name`).
pub fn register_clone(
    agents_root: &std::path::Path,
    name: &str,
    display_name: &str,
    description: &str,
    version: &str,
) -> std::io::Result<()> {
    let exe = std::env::current_exe()
        .map(|p| p.to_string_lossy().to_string())
        .unwrap_or_else(|_| "aginx-carrier".to_string());
    let doc = AgentToml {
        id: name.to_string(),
        name: if display_name.trim().is_empty() {
            name.to_string()
        } else {
            display_name.to_string()
        },
        agent_type: "aginx-carrier".to_string(),
        description: description.trim().to_string(),
        version: version.trim().to_string(),
        output: "claude-stream-json".to_string(),
        command: CommandToml {
            path: exe,
            args: vec!["acp".to_string(), "--clone".to_string(), name.to_string()],
        },
        session: SessionToml {
            resume_args: vec!["--session".to_string(), "${SESSION_ID}".to_string()],
        },
    };
    let body = toml::to_string_pretty(&doc).map_err(std::io::Error::other)?;
    let dir = agents_root.join(name);
    std::fs::create_dir_all(&dir)?;
    std::fs::write(
        dir.join("aginx.toml"),
        format!(
            "# Auto-generated by aginx-carrier clone_install — 分身装好即入网。\n\
             # 网关扫 ~/.aginx/agents/*/aginx.toml 发现本分身；删除分身时自动移除。\n{body}"
        ),
    )
}

/// Remove the registration (agent killed / clone uninstalled). Missing file
/// is fine — nothing to clean up.
pub fn unregister_clone(agents_root: &std::path::Path, name: &str) -> std::io::Result<()> {
    let dir = agents_root.join(name);
    match std::fs::remove_dir_all(&dir) {
        Ok(()) => Ok(()),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(e),
    }
}

/// `register_clone` against the default `~/.aginx/agents/` root.
pub fn register_clone_default(
    name: &str,
    display_name: &str,
    description: &str,
    version: &str,
) -> std::io::Result<()> {
    register_clone(&default_agents_root(), name, display_name, description, version)
}

/// Whether `~/.aginx/agents/<name>/aginx.toml` already exists. Boot-time
/// reconciliation skips existing registrations to preserve manual edits.
pub fn registration_exists_default(name: &str) -> bool {
    default_agents_root().join(name).join("aginx.toml").is_file()
}

/// `unregister_clone` against the default `~/.aginx/agents/` root.
pub fn unregister_clone_default(name: &str) -> std::io::Result<()> {
    unregister_clone(&default_agents_root(), name)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn registration_round_trips_through_gateway_shape() {
        let root = tempfile::tempdir().unwrap();
        register_clone(root.path(), "86bus", "86巴士助手", "查票查班线", "3")
            .unwrap();
        let raw = std::fs::read_to_string(root.path().join("86bus/aginx.toml")).unwrap();
        let cfg: toml::Value = toml::from_str(&raw).unwrap();
        assert_eq!(cfg["id"].as_str(), Some("86bus"));
        assert_eq!(cfg["name"].as_str(), Some("86巴士助手"));
        assert_eq!(cfg["agent_type"].as_str(), Some("aginx-carrier"));
        let cmd = &cfg["command"];
        let args: Vec<String> = cmd["args"].clone().try_into().unwrap();
        assert_eq!(args[2], "86bus");
        // Gateway discovery requires an absolute existing path (or bare name).
        let path = cmd["path"].as_str().unwrap();
        assert!(path.starts_with('/') && std::path::Path::new(path).exists());
        // 会话契约：方言声明 + resume_args（网关只在拿到 sessionId 时追加）。
        assert_eq!(cfg["output"].as_str(), Some("claude-stream-json"));
        let resume: Vec<String> = cfg["session"]["resume_args"].clone().try_into().unwrap();
        assert_eq!(resume, vec!["--session".to_string(), "${SESSION_ID}".to_string()]);
    }

    #[test]
    fn empty_display_name_falls_back_to_clone_name() {
        let root = tempfile::tempdir().unwrap();
        register_clone(root.path(), "demo", "", "", "").unwrap();
        let raw = std::fs::read_to_string(root.path().join("demo/aginx.toml")).unwrap();
        let cfg: toml::Value = toml::from_str(&raw).unwrap();
        assert_eq!(cfg["name"].as_str(), Some("demo"));
        // Empty description/version are omitted, not written as blank lines.
        assert!(cfg.get("description").is_none());
        assert!(cfg.get("version").is_none());
    }

    #[test]
    fn unregister_removes_dir_and_tolerates_missing() {
        let root = tempfile::tempdir().unwrap();
        register_clone(root.path(), "demo", "Demo", "", "").unwrap();
        unregister_clone(root.path(), "demo").unwrap();
        assert!(!root.path().join("demo").exists());
        // Second removal is a no-op, not an error.
        unregister_clone(root.path(), "demo").unwrap();
    }
}
